### ISSUE TITLE
Out of wrapper issue

### ISSUE THREAD

**Issue by bietdoikiem** [hungthezorba/tendermate-front-end#13]
**Describe the bug**
Mismatched placement of the ProjectCard component in Project-Manage's page which leads to overflow-x of the page. This bug happened in high resolution (FHD 1920x1080)

**To Reproduce**
1. Use FHD Monitor
2. Navigate to ProjectManage page
3. See error

**Expected behavior**
The card should be in the wrapper component not outside

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser MS Edge
 - Version Latest

**Additional context**
Please fix asap

**Comment by hungthezorba** [comment]
Closed in PR #14
